version: '3.8'

services:
  web:
    build: .
    container_name: kairo_web
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./kairo.db:/app/kairo.db
      - ./mangas_data:/app/mangas_data
      - ./images:/app/images
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis

  updater:
    build: .
    container_name: kairo_updater
    restart: always
    command: python auto_updater.py
    volumes:
      - ./kairo.db:/app/kairo.db

      - ./mangas_data:/app/mangas_data
      - ./images:/app/images
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - web

  celery_worker:
    build: .
    container_name: kairo_celery
    restart: always
    command: celery -A celery_app worker --loglevel=info -P threads -c 4
    volumes:
      - ./kairo.db:/app/kairo.db
      - ./mangas_data:/app/mangas_data
      - ./images:/app/images
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - web

  redis:
    image: redis:alpine
    container_name: kairo_redis
    restart: always
    ports:
      - 6379:6379

  chat:
    build: .
    container_name: kairo_chat
    restart: always
    command: python chat_server.py 5001
    volumes:
      - ./kairo.db:/app/kairo.db
      - ./chat_messages.db:/app/chat_messages.db
    depends_on:
      - web

  nginx:
    image: nginx:alpine
    container_name: kairo_nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web
      - chat
